### ISSUE TITLE
qtav Qmlplayer 

### ISSUE THREAD

**Issue by SatyanarayanaEpigon** [wang-bin/QtAV#1290]
i compiled qtav in Qt android 5.13.1  and trying to run application QMlplayer while startup application i am getting below error how to solve

W linker  : Warning: unable to normalize "C"
E AndroidRuntime: FATAL EXCEPTION: qtMainLoopThread
E AndroidRuntime: Process: org.qtav.qmlplayer, PID: 18434
E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libswresample.so" not found
E AndroidRuntime: 	at java.lang.Runtime.load0(Runtime.java:928)
E AndroidRuntime: 	at java.lang.System.load(System.java:1621)
E AndroidRuntime: 	at org.qtproject.qt5.android.QtNative$2.run(QtNative.java:199)
E AndroidRuntime: 	at org.qtproject.qt5.android.QtThread$2.run(QtThread.java:87)
E AndroidRuntime: 	at org.qtproject.qt5.android.QtThread$1.run(QtThread.java:61)
E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)

dlopen failed and crashing

**Comment by wang-bin** [comment]
build ffmpeg so files into you apk

**Comment by SatyanarayanaEpigon** [comment]
how to  build ffmpeg so files into you apk
