### ISSUE TITLE
trying to support avdevice

### ISSUE THREAD

**Issue by sherpya** [wang-bin/QtAV#298]
I'm trying to support avdevice via forcing input format, I've made a branch
https://github.com/sherpya/QtAV/tree/avdevice
but the video lags, video thread spams a lot of "delay x/x" and after a while the application crashes

in readFrame():

`memcpy(encoded.data(), packet.data, encoded.capacity());`

crashes even if it just reads `packet.size` from packet.data

maybe the frame decoding fails?

I suspect QtAV is not aware of the fps (for the delay) and it misses a check somewhere (for the crash)

any idea?
##

**Comment by wang-bin** [comment]
fixed in 8bde621df909886a1d54073fec903f48c9a74b8d
please confirm it

**Comment by sherpya** [comment]
first time works fine, then on linux after stop and play again in crashes in ffmpeg (2.5.3)

```
0x00007ffff468270a in ?? () from /usr/lib/x86_64-linux-gnu/libavdevice-ffmpeg.so.56
(gdb) bt
#0  0x00007ffff468270a in ?? () from /usr/lib/x86_64-linux-gnu/libavdevice-ffmpeg.so.56
#1  0x00007ffff21cdb0e in av_buffer_unref () from /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54
#2  0x00007ffff2b86205 in av_packet_unref ()
   from /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56
#3  0x00007ffff7b5f596 in QtAV::Packet::operator=(QtAV::Packet const&) ()
   from /usr/lib/x86_64-linux-gnu/libQtAV.so.1
#4  0x00007ffff7b4ca4a in QtAV::AVDemuxer::readFrame() ()
   from /usr/lib/x86_64-linux-gnu/libQtAV.so.1
#5  0x00007ffff7b53ea0 in QtAV::AVDemuxThread::run() ()
   from /usr/lib/x86_64-linux-gnu/libQtAV.so.1
#6  0x00007ffff5def0de in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff58a30a4 in start_thread (arg=0x7fffca8e2700) at pthread_create.c:309
#8  0x00007ffff4db5ccd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

Also: pause screws playing and you should inhibit playback rate other than 1.0
