### ISSUE TITLE
Seeking bug when the playback rate is bigger than 1.0 (speed)

### ISSUE THREAD

**Issue by tomicooler** [wang-bin/QtAV#423]
Hello,

I have found a bug using the C++ player example.

My environment:
- Up to date Archlinux
- QtAV 1.6 from the GIT (4b0643ffa9e4e12c95f3ee7d87842ea3ef5fc49b)

The reproduction is quite easy:
1. Load a simple video file (I used the big buck bunny trailer from webmfiles)
2. Change to speed to 10.0 (playback rate)
3. Seek to random positions (just click on the seekbar multiple times)

There are two different outcomes of this:
 a, the video playback stops with some error, but the player is still running and the video can be played again
 b, the video player freezes

If the speed is 1.0, then I can seek a lot without any issue, but in some cases the image won't update on the UI but the seekbar keeps moving.

Any information I shall provide?

Thank you for your help!

Here is a stacktrace, when the player stuck:

Thread 1 (Thread 0x7ffff7f3e7c0 (LWP 7626)):
#0  0x00007ffff62139af in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0

No symbol table info available.
#1  0x00007ffff67648fb in QWaitCondition::wait(QReadWriteLock*, unsigned long) () from /usr/lib/libQt5Core.so.5

No symbol table info available.
#2  0x00007ffff7aeb8cf in QtAV::BlockingQueue<QRunnable*, QQueue>::take (this=0xe9fa28) at /home/tomi/qt_workspace/QtAV/src/utils/BlockingQueue.h:169

```
    __PRETTY_FUNCTION__ = "T QtAV::BlockingQueue<T, Container>::take() [with T = QRunnable*; Container = QQueue]"
    locker = {q_val = 15333961}
    t = 0x7fffffffce20
```
#3  0x00007ffff7b5144e in QtAV::ExtractThread::addTask (this=0xe9fa10, t=0xf0f890) at /home/tomi/qt_workspace/QtAV/src/VideoFrameExtractor.cpp:62

```
    task = 0x2b95
```
#4  0x00007ffff7b50fcb in QtAV::VideoFrameExtractor::extract (this=0xe9f900) at /home/tomi/qt_workspace/QtAV/src/VideoFrameExtractor.cpp:491

```
    d = @0xe9f9a0: {<DPtrPrivate<QtAV::VideoFrameExtractor>> = {_vptr.DPtrPrivate = 0x7ffff7dcc490 <vtable for QtAV::VideoFrameExtractorPrivate+16>, dptr_p_ptr = 0x7ffff59d7c58 <main_arena+88>}, extracted = true, async = true, has_video = true, loading = 245, auto_extract = false, auto_precision = true, seek_count = 71, position = 11157, precision = 500, source = {static null = {<No data fields>}, d = 0xf0c190}, demuxer = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = 0x7ffff6b82980 <QObject::staticMetaObject>, stringdata = 0x7ffff7b78c40 <qt_meta_stringdata_QtAV__AVDemuxer>, data = 0x7ffff7b78e40 <qt_meta_data_QtAV__AVDemuxer>, static_metacall = 0x7ffff7b54b76 <QtAV::AVDemuxer::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, d = {d = 0xb616a0}}, decoder = {d = 0x7fffac0059a0}, frame = {<QtAV::Frame> = {_vptr.Frame = 0x7ffff7dcb2d0 <vtable for QtAV::VideoFrame+16>, d_ptr = {d = 0x7fffac09b220}}, <No data fields>}, codecs = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = -1}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x771f50}, d = 0x771f50}}, <No data fields>}, thread = {<QThread> = {<No data fields>}, stop = false, tasks = {_vptr.BlockingQueue = 0x7ffff7dca250 <vtable for QtAV::BlockingQueue<QRunnable*, QQueue>+16>, block_empty = true, block_full = true, cap = 1, thres = 1, queue = {<QList<QRunnable*>> = {<QListSpecialMethods<QRunnable*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = -1}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0xec9a80}, d = 0xec9a80}}, <No data fields>}, lock = {d = 0xf93790}, block_change_lock = {d = 0xeb1810}, cond_full = {d = 0xb61b80}, cond_empty = {d = 0xb61bf0}, empty_callback = {d = 0x0}, threshold_callback = {d = 0x0}, full_callback = {d = 0x0}}}, static dec_opt_framedrop = {{d = 0x9e1000, e = 0x9e1000}}, static dec_opt_normal = {{d = 0xea7c90, e = 0xea7c90}}}
```
#5  0x00007ffff7794ec0 in QtAV::VideoPreviewWidget::preview (this=0x104dec0) at /home/tomi/qt_workspace/QtAV/widgets/VideoPreviewWidget.cpp:63

No locals.
#6  0x000000000043131e in MainWindow::onTimeSliderHover (this=0x7fffffffdef0, pos=275, value=11075) at /home/tomi/qt_workspace/QtAV/examples/player/MainWindow.cpp:1261

```
    gpos = {xp = 2551, yp = 582}
    w = 0
    h = 0
```
#7  0x000000000045a6a8 in MainWindow::qt_static_metacall (_o=0x7fffffffdef0, _c=QMetaObject::InvokeMetaMethod, _id=39, _a=0x7fffffffd150) at ../../.moc/5.4.1/player/moc_MainWindow.cpp:349

```
    _t = 0x7fffffffdef0
```
#8  0x00007ffff697f3c9 in QMetaObject::activate(QObject_, int, int, void_*) () from /usr/lib/libQt5Core.so.5

No symbol table info available.
#9  0x000000000045b45d in Slider::onHover (this=0x72a490, _t1=275, _t2=11075) at ../../.moc/5.4.1/player/moc_Slider.cpp:158

```
    _a = {0x0, 0x7fffffffd144, 0x7fffffffd140}
```
#10 0x000000000043cc73 in Slider::mouseMoveEvent (this=0x72a490, e=0x7fffffffd610) at /home/tomi/qt_workspace/QtAV/examples/player/Slider.cpp:121

```
    o = 14
    v = 11075
```
##

**Comment by tomicooler** [comment]
I tested it with version 1.8, the issue is no longer exists. Thanks!
