### ISSUE TITLE
AudioResampler example

### ISSUE THREAD

**Issue by thefastman** [wang-bin/QtAV#767]
Hi ! Can you give base example how to use AudioResampler ?
thanks.

**Comment by cgilles** [comment]
Hi

For digiKam, we need to encode audio frames with video frame for a video slideshow tool.

I take a look to QtAv sample codes about AudioFrame use and AudioResampler. One is examples/audiopipeline. 

I compiled the current code from git/master and tried to use this CLI tool to play a simple mp3 file to audio output. I crash violently in AudioFrame.to() when frame is resampled to the output audio format : 

[gilles@localhost bin]$ gdb --args ./audiopipeline 10\ -\ Poorman.mp3 
GNU gdb (GDB) 1-15.mga6 (Mageia release 6)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-mageia-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./audiopipeline...done.
(gdb) r
Starting program: /home/gilles/Devel/QtAV/build/bin/audiopipeline 10\ -\ Poorman.mp3
Missing separate debuginfos, use: debuginfo-install glibc-2.22-24.mga6.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
"usage: " "audiopipeline url"
QtAV 1.11.0(May 30 2017, 22:17:57)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
QtAV 1.11.0(May 30 2017, 22:17:57)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org
"Build with Qt-5.6.2"
"FFmpeg/Libav configuration: --prefix=/usr --enable-shared --libdir=/usr/lib64 --shlibdir=/usr/lib64 --incdir=/usr/include --disable-stripping --enable-postproc --enable-gpl --enable-pthreads --enable-libtheora --enable-libvorbis --disable-encoder=vorbis --enable-libvpx --enable-runtime-cpudetect --enable-libdc1394 --enable-libschroedinger --enable-librtmp --enable-libspeex --enable-libfreetype --enable-libnut --enable-libgsm --enable-libcelt --enable-libopus --enable-libopencv --enable-libopenjpeg --enable-libtwolame --enable-libxavs --enable-frei0r --enable-libmodplug --enable-libass --enable-gnutls --enable-libcdio --enable-libpulse --enable-libv4l2 --enable-avresample --enable-opencl --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-version3 --enable-libx264 --enable-libx265 --enable-libvo-amrwbenc --enable-libxvid"
"Build with avutil-55.58.100"
"Build with avcodec-57.89.100"
"Build with avformat-57.71.100"
"Build with avfilter-6.82.100"
"Build with avdevice-57.6.100"
"Build with avresample-3.5.0"
"Build with swresample-2.7.100"
"Build with swscale-4.6.100"
Registered audio backends:  ("Pulse", "null")
"all closed and reseted"
"avformat_open_input: d->format_ctx:'0x644fa0', url:'10 - Poorman.mp3'..."
"avformat_open_input: url:'10 - Poorman.mp3' ret:0"
"avfmtctx.flags: 2097665, iformat.flags"
"QtAV::AudioDecoderFFmpeg thread type: Single, count: 1"
"src audio parameters 'channel layout(or channels), sample rate and sample format must be set before initialize resampler"
[New Thread 0x7fffe1103700 (LWP 23091)]
"PulseAudio 10.0.0, protocol: 32, server protocol: 4294967295"
Input:  QtAV::AudioFormat(44100Hz, 2Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "s16p")
Output:  QtAV::AudioFormat(44100Hz, 2Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "s16p")
"(repeat 1)src audio parameters 'channel layout(or channels), sample rate and sample format must be set before initialize resampler\nswr speed=1.00"
"out: {cl: 3, fmt: s16, freq: 44100}"
"in {cl: 3, fmt: s16p, freq: 44100}"
"swr speed=1.00"
"out: {cl: 3, fmt: s16p, freq: 44100}"
"in {cl: 3, fmt: s16p, freq: 44100}"

Thread 1 "audiopipeline" received signal SIGSEGV, Segmentation fault.
0x00007ffff388d09c in conv_AV_SAMPLE_FMT_S16_to_AV_SAMPLE_FMT_S16 () from /lib64/libswresample.so.2
Missing separate debuginfos, use: debuginfo-install lib64alsa2-1.1.4-1.mga6.x86_64 lib64ass9-0.13.6-1.mga6.x86_64 lib64asyncns0-0.8-9.mga6.x86_64 lib64avcodec57-3.3.1-1.mga6.tainted.x86_64 lib64avfilter6-3.3.1-1.mga6.tainted.x86_64 lib64avformat57-3.3.1-1.mga6.tainted.x86_64 lib64avresample3-3.3.1-1.mga6.tainted.x86_64 lib64avutil55-3.3.1-1.mga6.tainted.x86_64 lib64bsd0-0.8.3-1.mga6.x86_64 lib64bzip2_1-1.0.6-10.mga6.x86_64 lib64cdio-paranoia2-10.2.0.93.1-8.mga6.x86_64 lib64cdio16-0.94-1.mga6.x86_64 lib64celt0_2-0.11.3-6.mga6.x86_64 lib64dbus1_3-1.10.16-1.mga6.x86_64 lib64dc1394_22-2.2.5-2.mga6.x86_64 lib64drm2-2.4.80-1.mga6.x86_64 lib64expat1-2.2.0-2.mga6.x86_64 lib64ffi6-3.2.1-5.mga6.x86_64 lib64flac8-1.3.2-1.mga6.x86_64 lib64fontconfig1-2.12.1-2.mga6.x86_64 lib64freetype6-2.7.1-2.mga6.tainted.x86_64 lib64fribidi0-0.19.7-3.mga6.x86_64 lib64gcrypt20-1.7.6-1.mga6.x86_64 lib64glapi0-17.1.1-1.mga6.tainted.x86_64 lib64glib2.0_0-2.52.2-2.mga6.x86_64 lib64gmp10-6.1.2-1.mga6.x86_64 lib64gnutls30-3.5.12-1.mga6.x86_64 lib64gpg-error0-1.24-1.mga6.x86_64 lib64graphite2_3-1.3.10-1.mga6.x86_64 lib64gsm1-1.0.16-1.mga6.x86_64 lib64harfbuzz0-1.3.2-5.mga6.x86_64 lib64icu58-58.2-3.mga6.x86_64 lib64jack0-1.9.10-6.mga6.x86_64 lib64jpeg8-1.5.1-1.mga6.x86_64 lib64lzma5-5.2.3-1.mga6.x86_64 lib64mesagl1-17.1.1-1.mga6.tainted.x86_64 lib64modplug1-0.8.9.0-1.mga6.x86_64 lib64mp3lame0-3.99.5-13.mga6.tainted.x86_64 lib64nut0-0.0.675-8.mga6.x86_64 lib64ogg0-1.3.2-4.mga6.x86_64 lib64opencl1-2.2.11-1.mga6.x86_64 lib64opencore-amr0-0.1.3-1.mga6.tainted.x86_64 lib64opencv_core2.4-2.4.12.3-5.mga6.x86_64 lib64opencv_imgproc2.4-2.4.12.3-5.mga6.x86_64 lib64openjpeg5-1.5.2-8.mga6.x86_64 lib64openssl1.0.0-1.0.2l-1.mga6.x86_64 lib64opus0-1.1.5-1.mga6.x86_64 lib64orc0.4_0-0.4.26-1.mga6.x86_64 lib64p11-kit0-0.23.2-2.mga6.x86_64 lib64pcre1-8.40-2.mga6.x86_64 lib64pcre16_0-8.40-2.mga6.x86_64 lib64png16_16-1.6.29-1.mga6.x86_64 lib64postproc54-3.3.1-1.mga6.tainted.x86_64 lib64pulseaudio0-10.0-1.mga6.x86_64 lib64pulsecommon10.0-10.0-1.mga6.x86_64 lib64qt5core5-5.6.2-10.mga6.x86_64 lib64qt5gui5-5.6.2-10.mga6.x86_64 lib64raw1394_11-2.1.2-1.mga6.x86_64 lib64rtmp1-2.4-0.git20160101.3.mga6.tainted.x86_64 lib64schroedinger1.0_0-1.0.11-8.mga6.x86_64 lib64sdl2.0_0-2.0.5-2.mga6.x86_64 lib64sndfile1-1.0.28-1.mga6.x86_64 lib64speex1-1.2-0.rc2.2.mga6.x86_64 lib64swresample2-3.3.1-1.mga6.tainted.x86_64 lib64swscaler4-3.3.1-1.mga6.tainted.x86_64 lib64systemd0-230-10.mga6.x86_64 lib64tasn1_6-4.10-2.mga6.x86_64 lib64theoradec1-1.1.1-11.mga6.x86_64 lib64theoraenc1-1.1.1-11.mga6.x86_64 lib64twolame0-0.3.13-7.mga6.x86_64 lib64udev1-230-10.mga6.x86_64 lib64unistring2-0.9.7-1.mga6.x86_64 lib64usb1.0_0-1.0.21-1.mga6.x86_64 lib64v4l0-1.12.5-1.mga6.x86_64 lib64va1-1.7.3-3.mga6.x86_64 lib64vdpau1-1.1.1-2.mga6.x86_64 lib64vo-amrwbenc0-0.1.3-2.mga6.tainted.x86_64 lib64vorbis0-1.3.5-2.mga6.x86_64 lib64vorbisenc2-1.3.5-2.mga6.x86_64 lib64vpx3-1.5.0-3.mga6.x86_64 lib64wrap0-7.6-47.mga6.x86_64 lib64x11-xcb1-1.6.5-1.mga6.x86_64 lib64x11_6-1.6.5-1.mga6.x86_64 lib64x264_148-0.148-0.20170120.stable.5.mga6.tainted.x86_64 lib64x265_102-2.2-1.mga6.tainted.x86_64 lib64xau6-1.0.8-7.mga6.x86_64 lib64xavs1-0.1.55-8.mga6.x86_64 lib64xcb-dri2_0-1.12-2.mga6.x86_64 lib64xcb-dri3_0-1.12-2.mga6.x86_64 lib64xcb-glx0-1.12-2.mga6.x86_64 lib64xcb-present0-1.12-2.mga6.x86_64 lib64xcb-shape0-1.12-2.mga6.x86_64 lib64xcb-shm0-1.12-2.mga6.x86_64 lib64xcb-sync1-1.12-2.mga6.x86_64 lib64xcb-xfixes0-1.12-2.mga6.x86_64 lib64xcb1-1.12-2.mga6.x86_64 lib64xdamage1-1.1.4-8.mga6.x86_64 lib64xdmcp6-1.1.2-5.mga6.x86_64 lib64xext6-1.3.3-4.mga6.x86_64 lib64xfixes3-5.0.3-1.mga6.x86_64 lib64xml2_2-2.9.4-4.mga6.x86_64 lib64xshmfence1-1.2-2.mga6.x86_64 lib64xvidcore4-1.3.4-3.mga6.tainted.x86_64 lib64xxf86vm1-1.1.4-2.mga6.x86_64 lib64zlib1-1.2.11-4.mga6.x86_64 libgcc1-5.4.0-4.mga6.x86_64 libstdc++6-5.4.0-4.mga6.x86_64
(gdb) bt
#0  0x00007ffff388d09c in conv_AV_SAMPLE_FMT_S16_to_AV_SAMPLE_FMT_S16 () from /lib64/libswresample.so.2
#1  0x00007ffff388ecce in swri_audio_convert () from /lib64/libswresample.so.2
#2  0x00007ffff38953e2 in swr_convert () from /lib64/libswresample.so.2
#3  0x00007ffff7a2fab1 in QtAV::AudioResamplerFF::convert (this=0x620dd0, data=0x6490c8)
    at /home/gilles/Devel/QtAV/src/AudioResamplerTemplate.cpp:103
#4  0x00007ffff7a58fe8 in QtAV::AudioFrame::to (this=0x7fffffffd5f0, fmt=...) at /home/gilles/Devel/QtAV/src/AudioFrame.cpp:226
#5  0x0000000000402c60 in main (argc=2, argv=0x7fffffffd9b8) at /home/gilles/Devel/QtAV/examples/audiopipeline/main.cpp:85
(gdb) 

The mp3 file as nothing special : 

[gilles@localhost bin]$ ffmpeg -i 10\ -\ Poorman.mp3 
ffmpeg version 3.3.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --prefix=/usr --enable-shared --libdir=/usr/lib64 --shlibdir=/usr/lib64 --incdir=/usr/include --disable-stripping --enable-postproc --enable-gpl --enable-pthreads --enable-libtheora --enable-libvorbis --disable-encoder=vorbis --enable-libvpx --enable-runtime-cpudetect --enable-libdc1394 --enable-libschroedinger --enable-librtmp --enable-libspeex --enable-libfreetype --enable-libnut --enable-libgsm --enable-libcelt --enable-libopus --enable-libopencv --enable-libopenjpeg --enable-libtwolame --enable-libxavs --enable-frei0r --enable-libmodplug --enable-libass --enable-gnutls --enable-libcdio --enable-libpulse --enable-libv4l2 --enable-avresample --enable-opencl --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-version3 --enable-libx264 --enable-libx265 --enable-libvo-amrwbenc --enable-libxvid
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, mp3, from '10 - Poorman.mp3':
  Metadata:
    comment         : plixid.com
    date            : 2017
    genre           : Electronic
    disc            : 1
    composer        : Depeche Mode
    TIT1            : Depeche Mode
    artist          : Depeche Mode
    album_artist    : Depeche Mode
    compilation     : 0
    title           : Poorman
    track           : 10
    album           : Spirit
  Duration: 00:04:25.87, start: 0.025056, bitrate: 321 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, s16p, 320 kb/s
    Metadata:
      encoder         : LAME3.99r
    Side data:
      replaygain: track gain - -6.800000, track peak - unknown, album gain - unknown, album peak - unknown, 
    Stream #0:1: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 600x600 [SAR 72:72 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)

Note : in my digiKam code to encode frames as a video slideshow, i see exactly the same problem at the same place when audio frame are resampled. My code is mostly based on audiopipeline code to decode audio frame and re-encode it to another format for a mix with a video stream.

So i need also some help or guidance about AudioResampler use. This is a know bug ? This is a problem with my ffmpeg version ?

Thanks in advance
