### ISSUE TITLE
QtAV/examples/audiopipeline/main.cpp 不能播放声音 ...

### ISSUE THREAD

**Issue by nulijiabei** [wang-bin/QtAV#772]
使用 QtAV/examples/audiopipeline/main.cpp 不能播放声音 ...

	Starting E:\build-untitled-Desktop_Qt_5_7_0_MSVC2015_32bit-Debug\debug\untitled.exe...
	AudioResampler::Register(..., FFmpeg)
	Singleton 00927E90 created...
	AudioOutputBackend::Register(..., XAudio2)
	Singleton 009282E8 created...
	AudioOutputBackend::Register(..., DirectSound)
	VideoDecoder::Register(..., CUDA)
	Singleton 00928340 created...
	VideoDecoder::Register(..., D3D11)
	VideoDecoder::Register(..., DXVA)
	VideoRenderer::Register(..., OpenGLWindow)
	Singleton 00928398 created...
	SubtitleProcessor::Register(..., FFmpeg)
	Singleton 0092C5C8 created...
	AudioDecoder::Register(..., FFmpeg)
	Singleton 0092C1A8 created...
	AudioEncoder::Register(..., FFmpeg)
	Singleton 0092C0A0 created...
	ImageConverter::Register(..., FFmpeg)
	Singleton 0092C048 created...
	MediaIO::Register(..., QIODevice)
	Singleton 0092C308 created...
	MediaIO::Register(..., QFile)
	AudioOutputBackend::Register(..., null)
	VideoDecoder::Register(..., FFmpeg)
	VideoEncoder::Register(..., FFmpeg)
	Singleton 0092C360 created...
	QtAV 1.11.0(Nov  4 2016, 12:43:46)
	Multimedia framework base on Qt and FFmpeg.
	Distributed under the terms of LGPLv2.1 or later.
	Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
	Donate: http://qtav.org/donate.html
	Source: https://github.com/wang-bin/QtAV
	Home page: http://qtav.org
	AudioOutputBackend::id("XAudio2")
	QtAV 1.11.0(Nov  4 2016, 12:43:46)
	Multimedia framework base on Qt and FFmpeg.
	Distributed under the terms of LGPLv2.1 or later.
	Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
	Donate: http://qtav.org/donate.html
	Source: https://github.com/wang-bin/QtAV
	Home page: http://qtav.org
	"Build with Qt-5.7.0"
	"FFmpeg/Libav configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib"
	"Build with avutil-55.29.100"
	"Warning: avutil runtime version 55.30.100 mismatch!"
	"Build with avcodec-57.55.101"
	"Warning: avcodec runtime version 57.57.101 mismatch!"
	"Build with avformat-57.49.100"
	"Warning: avformat runtime version 57.50.100 mismatch!"
	"Build with avfilter-6.62.100"
	"Build with avdevice-57.0.102"
	"Build with swresample-2.1.100"
	"Build with swscale-4.1.100"
	Registered audio backends:  ("XAudio2", "DirectSound", "null")
	"XAudio2_9"
	AudioDecoder::id("FFmpeg")
	playing: 0.000...
	"Build with XAudio2 from Win8 or later SDK"
	"Try symbol 'XAudio2Create' from WinSDK dll"
	"xaudio2: 0x4b30560"
	"all closed and reseted"
	"avformat_open_input: d->format_ctx:'0x101b480', url:'E://Content//a.mp4'..."
	"avformat_open_input: url:'E://Content//a.mp4' ret:0"
	"avfmtctx.flags: 2097665, iformat.flags"
	"QtAV::AudioDecoderFFmpeg thread type: Single, count: 1"
	"src audio parameters 'channel layout(or channels), sample rate and sample format must be set before initialize resampler"
	"(repeat 1)src audio parameters 'channel layout(or channels), sample rate and sample format must be set before initialize resampler\nsource_voice:0x4b3d098"
	Input:  QtAV::AudioFormat(44100Hz, 4Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "fltp")
	Output:  QtAV::AudioFormat(44100Hz, 4Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "fltp")
	"swr speed=1.00"
	"out: {cl: 3, fmt: flt, freq: 44100}"
	"in {cl: 3, fmt: fltp, freq: 44100}"
	"swr speed=1.00"
	"out: {cl: 3, fmt: fltp, freq: 44100}"
	"in {cl: 3, fmt: fltp, freq: 44100}"

----

	E:\build-untitled-Desktop_Qt_5_7_0_MSVC2015_32bit-Debug\debug>gdb untitled.exe
	GNU gdb (GDB) 7.7.50.20140303-cvs
	Copyright (C) 2014 Free Software Foundation, Inc.
	License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
	This is free software: you are free to change and redistribute it.
	There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
	and "show warranty" for details.
	This GDB was configured as "i686-pc-mingw32".
	Type "show configuration" for configuration details.
	For bug reporting instructions, please see:
	<http://www.gnu.org/software/gdb/bugs/>.
	Find the GDB manual and other documentation resources online at:
	<http://www.gnu.org/software/gdb/documentation/>.
	For help, type "help".
	Type "apropos word" to search for commands related to "word".

	This binary was built by Equation Solution <http://www.Equation.com>...
	Reading symbols from untitled.exe...(no debugging symbols found)...done.
	(gdb) r
	Starting program: E:\build-untitled-Desktop_Qt_5_7_0_MSVC2015_32bit-Debug\debug\untitled.exe
	[New Thread 6916.0x78c]
	[New Thread 6916.0x1460]
	[New Thread 6916.0xc34]
	[New Thread 6916.0x780]
	warning: QtAV 1.11.0(Nov  4 2016, 12:43:46)
	Multimedia framework base on Qt and FFmpeg.
	Distributed under the terms of LGPLv2.1 or later.
	Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
	Donate: http://qtav.org/donate.html
	Source: https://github.com/wang-bin/QtAV
	Home page: http://qtav.org

	warning: "Build with Qt-5.7.0"

	warning: "FFmpeg/Libav configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib"

	warning: "Build with avutil-55.29.100"

	warning: "Warning: avutil runtime version 55.30.100 mismatch!"

	warning: "Build with avcodec-57.55.101"

	warning: "Warning: avcodec runtime version 57.57.101 mismatch!"

	warning: "Build with avformat-57.49.100"

	warning: "Warning: avformat runtime version 57.50.100 mismatch!"

	warning: "Build with avfilter-6.62.100"

	warning: "Build with avdevice-57.0.102"

	warning: "Build with swresample-2.1.100"

	warning: "Build with swscale-4.1.100"

	warning: Registered audio backends:  ("XAudio2", "DirectSound", "null")

	warning: "XAudio2_9"

	warning: "Build with XAudio2 from Win8 or later SDK"

	warning: "Try symbol 'XAudio2Create' from WinSDK dll"

	warning: "xaudio2: 0x53105a0"

	warning: "all closed and reseted"

	warning: "avformat_open_input: d->format_ctx:'0x4cec1a0', url:'E://Content//a.mp4'..."

	warning: "avformat_open_input: url:'E://Content//a.mp4' ret:0"

	warning: "avfmtctx.flags: 2097665, iformat.flags"

	warning: "QtAV::AudioDecoderFFmpeg thread type: Single, count: 1"

	warning: "src audio parameters 'channel layout(or channels), sample rate and sample format must be set before initialize resampler"

	[New Thread 6916.0x7c4]
	[New Thread 6916.0x24f8]
	[New Thread 6916.0x2d14]
	warning: "(repeat 1)src audio parameters 'channel layout(or channels), sample rate and sample format must be set before initialize resampler\nsource_voice:0x531d828"

	warning: Input:  QtAV::AudioFormat(44100Hz, 4Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "fltp")

	warning: Output:  QtAV::AudioFormat(44100Hz, 4Bytes, channelCount:2, channelLayout: "stereo", sampleFormat: "fltp")

	warning: "swr speed=1.00"

	warning: "out: {cl: 3, fmt: flt, freq: 44100}"

	warning: "in {cl: 3, fmt: fltp, freq: 44100}"

	warning: "swr speed=1.00"

	warning: "out: {cl: 3, fmt: fltp, freq: 44100}"

	warning: "in {cl: 3, fmt: fltp, freq: 44100}"

	Program received signal SIGSEGV, Segmentation fault.
	0x50072892 in ?? () from E:\build-untitled-Desktop_Qt_5_7_0_MSVC2015_32bit-Debug\debug\swresample-2.dll
	(gdb) bt
	#0  0x50072892 in ?? () from E:\build-untitled-Desktop_Qt_5_7_0_MSVC2015_32bit-Debug\debug\swresample-2.dll
	Cannot access memory at address 0xbc3c
	(gdb)

**Comment by nulijiabei** [comment]
Program received signal SIGSEGV, Segmentation fault.
	0x50072892 in ?? () from E:\build-untitled-Desktop_Qt_5_7_0_MSVC2015_32bit-Debug\debug\swresample-2.dll
	(gdb) bt
	#0  0x50072892 in ?? () from E:\build-untitled-Desktop_Qt_5_7_0_MSVC2015_32bit-Debug\debug\swresample-2.dll
	Cannot access memory at address 0xbc3c
	(gdb) print 0x50072892
	$1 = 1342646418
	(gdb) print 0xbc3c
	$2 = 48188
	(gdb)

**Comment by nulijiabei** [comment]
@wang-bin 🙏🙏🙏

**Comment by nulijiabei** [comment]
@wang-bin 🙏🙏🙏

**Comment by nulijiabei** [comment]
@wang-bin 🙏🙏🙏

**Comment by nulijiabei** [comment]
@wang-bin 能回一下吗 ...

**Comment by nulijiabei** [comment]
@wang-bin 

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f64f.png)

**Comment by nulijiabei** [comment]
看来等不到答复了 ...

**Comment by nulijiabei** [comment]
赶紧关闭，纯属蛋疼，........... 说多无益，赶紧离开 ...
